In [1]:
# Paso 0: Importar libreria Pandas

import pandas as pd

In [2]:
# Paso 1: Cargar DFs con csv generados

acerinox = pd.read_csv('acx.csv')
arcelor = pd.read_csv('mts.csv')

In [3]:
# Paso 2: Concatenar los diferentes DFs para tener un consolidado de Banking

resources = pd.concat([acerinox, arcelor], axis=0)

resources.reset_index(drop=True)

,id,ticker,empresa,date,open,high,low,close,adj close,volume
0,3,ACX,Acerinox,2019-01-02,8.640000,8.642000,8.350000,8.582000,5.994900,860864
1,3,ACX,Acerinox,2019-01-03,8.526000,8.576000,8.402000,8.406000,5.871956,860687
2,3,ACX,Acerinox,2019-01-04,8.516000,8.898000,8.510000,8.882000,6.204463,1662782
3,3,ACX,Acerinox,2019-01-07,8.994000,9.054000,8.776000,8.976000,6.270126,1209968
4,3,ACX,Acerinox,2019-01-08,8.968000,9.340000,8.968000,9.200000,6.426599,3245342
...,...,...,...,...,...,...,...,...,...,...
2645,7,MTS,Arcelor,2024-02-26,24.309999,24.340000,23.850000,24.040001,24.040001,279248
2646,7,MTS,Arcelor,2024-02-27,24.055000,24.469999,23.934999,24.370001,24.370001,155101
2647,7,MTS,Arcelor,2024-02-28,24.309999,24.309999,24.045000,24.100000,24.100000,134059
2648,7,MTS,Arcelor,2024-02-29,24.145000,24.225000,23.709999,24.129999,24.129999,282132
2649,7,MTS,Arcelor,2024-03-01,24.195000,24.200001,23.980000,24.084999,24.084999,162129

In [4]:
# Paso 3: Exportar el DF a csv

resources.to_csv('resources.csv')