In [1]:
# Paso 0: Importar libreria Pandas

import pandas as pd

In [2]:
# Paso 1: Cargar DFs con csv generados

grifols = pd.read_csv('grf.csv')
rovi = pd.read_csv('rovi.csv')

In [3]:
# Paso 2: Concatenar los diferentes DFs para tener un consolidado de Banking

pharma = pd.concat([grifols, rovi], axis=0)

pharma.reset_index(drop=True)

,id,ticker,empresa,date,open,high,low,close,adj close,volume
0,18,GRF,Grifols,2019-01-02,22.559999,22.730000,22.180000,22.730000,21.937431,488978
1,18,GRF,Grifols,2019-01-03,22.719999,22.930000,22.500000,22.809999,22.014643,3948479
2,18,GRF,Grifols,2019-01-04,23.090000,23.860001,22.809999,23.570000,22.748142,853831
3,18,GRF,Grifols,2019-01-07,23.590000,23.670000,23.309999,23.549999,22.728840,387963
4,18,GRF,Grifols,2019-01-08,23.590000,24.160000,23.590000,23.900000,23.066635,755013
...,...,...,...,...,...,...,...,...,...,...
2645,31,ROVI,Laboratorios Rovi,2024-02-26,71.150002,72.449997,71.000000,71.500000,71.500000,58417
2646,31,ROVI,Laboratorios Rovi,2024-02-27,69.550003,69.800003,64.250000,67.500000,67.500000,483613
2647,31,ROVI,Laboratorios Rovi,2024-02-28,67.199997,71.099998,67.199997,70.900002,70.900002,162449
2648,31,ROVI,Laboratorios Rovi,2024-02-29,71.500000,75.199997,71.199997,74.050003,74.050003,237952
2649,31,ROVI,Laboratorios Rovi,2024-03-01,74.699997,76.000000,74.050003,75.349998,75.349998,102505

In [4]:
# Paso 3: Exportar el DF a csv

pharma.to_csv('pharma.csv')